name: pydata-pdx-onnx
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - numpy
  - pip
  - pandas
  - pyarrow
  - python-graphviz
  - scikit-learn
  - matplotlib
  - h5py
  - pytorch
  - torchvision
  - cpuonly
  - pip:
    - onnxmltools
    - onnxruntime
